// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv7_Xsf04QnWgDo67yK7CGQDGer7ZVgiQ',
    appId: '1:115633477326:web:0f88b1fca2be4f2bb0629f',
    messagingSenderId: '115633477326',
    projectId: 'examapp-95938',
    authDomain: 'examapp-95938.firebaseapp.com',
    storageBucket: 'examapp-95938.appspot.com',
    measurementId: 'G-RHMM5VXVNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoECSDyvH8pgzr1Yf2i2sz3Pmz677iWBA',
    appId: '1:115633477326:android:42231ffc9a282911b0629f',
    messagingSenderId: '115633477326',
    projectId: 'examapp-95938',
    storageBucket: 'examapp-95938.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-HcyxTl5Y6Qz70CGBmFcQPM6CN6mbG_k',
    appId: '1:115633477326:ios:ba1b1d5e5d157f72b0629f',
    messagingSenderId: '115633477326',
    projectId: 'examapp-95938',
    storageBucket: 'examapp-95938.appspot.com',
    iosClientId:
        '115633477326-arch8j29trnhae5mnanv5bj3c298tnp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.examapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-HcyxTl5Y6Qz70CGBmFcQPM6CN6mbG_k',
    appId: '1:115633477326:ios:ba1b1d5e5d157f72b0629f',
    messagingSenderId: '115633477326',
    projectId: 'examapp-95938',
    storageBucket: 'examapp-95938.appspot.com',
    iosClientId:
        '115633477326-arch8j29trnhae5mnanv5bj3c298tnp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.examapp',
  );
}
